spring:
  datasource:
    auth:
      initialize: false
      url: jdbc:mysql://localhost/zenwherk_auth?useSSL=false
      username: root
      password:
      driverClassName: com.mysql.jdbc.Driver
      connectionTestQuery: SELECT 1
      maximumPoolSize: 5
    provisioning:
      initialize: false
      url: jdbc:mysql://localhost/zenwherk_api?useSSL=false
      username: root
      password:
      driverClassName: com.mysql.jdbc.Driver
      connectionTestQuery: SELECT 1
      maximumPoolSize: 5
logging:
  level:
    com.nuzur: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
server:
  port: 9999

