spring:
  datasource:
    auth:
      initialize: false
      url: jdbc:mysql://zenwherk-auth.cbt3wxqgkpus.us-east-1.rds.amazonaws.com/zenwherk_auth?useSSL=false
      username: zenwherk
      password: zenwherk-password
      driverClassName: com.mysql.jdbc.Driver
      connectionTestQuery: SELECT 1
      maximumPoolSize: 1
    provisioning:
      initialize: false
      url: jdbc:mysql://zenwherk.cbt3wxqgkpus.us-east-1.rds.amazonaws.com/zenwherk_api?useSSL=false
      username: zenwherk
      password: zenwherk-password
      driverClassName: com.mysql.jdbc.Driver
      connectionTestQuery: SELECT 1
      maximumPoolSize: 1


